app: helloworld
project: helloworld
repoURL: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/hello-groupe/helloworld-iac.git
path: k8s
environments:
- name: dev
  branch: dev
  namespace: helloworld-dev
- name: rec
  branch: rec
  namespace: helloworld-rec
- name: preprod
  branch: preprod
  namespace: helloworld-preprod
- name: prod
  branch: main
  namespace: helloworld
