app: helloworld
project: helloworld
repoURL: https://gitlab.com/k8s-gitops-lab/hello-groupe/helloworld-iac.git
manifestsPath: k8s
environments:
- name: dev
  branch: dev
  namespace: helloworld-dev
- name: rec
  branch: rec
  namespace: helloworld-rec
- name: preprod
  branch: preprod
  namespace: helloworld-preprod
- name: prod
  branch: main
  namespace: helloworld
