apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-helloworld-iac-repo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secrets
  target:
    name: gitlab-helloworld-iac-repo
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: http://gitlab-webservice-default.gitlab.svc.cluster.local:8181/hello-groupe/helloworld-iac.git
        username: root
        password: '{{ .password }}'
  data:
  - secretKey: password
    remoteRef:
      key: gitlab-gitlab-initial-root-password
      property: password
