apiVersion: v1
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: argocd
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:xmua2VRvH4kKRAUas2fGhj9g3QhvUyGqRR1hhxk6FhIC2tNYcaU9lFy//RLii+32Pw+SVFpfZSUhuzXEZnHMzCRxqll1V6dL+7JCLoswGms6WooJJ22t1f/kkhCJnWqYH0HTQgFS6VTDkoTtXEJxFvUhX0w0AwG4YecNE3LeolrTrBIkHwwodwdyr3lVgRkHc22iUgCooVSero1X01bfE2paPZrL/1ABsBblGiOnfteg198=,iv:qb0KpTk72NmUOSk01HCAipklDeG9o7tyIDtLLr/r5qk=,tag:2pk+aF9e34MQv5tfjiKnUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBocHdaRkpFc0krM0J3Vkhl
            SkxxVVVFdWhPbEVhMTFmVDZsNVR2OWIwV2pzCkxhamRNZzlna0Z1c282dndxWU5t
            MVRXbTJxWWt4dTMxbFU0eFEzN2RDZzAKLS0tIGc0YytUQWlhOStROXVQeGhxempB
            c0xIQ0ZwRnoyenBOOFdTYmI2T0Z5TVkKWe2TAQ6yOe/7OsqyscqRhku5DY5nbV8m
            7LreTdWva2Gke3NvZPu+n91A7njIIBlV/N0uOs154vCEewKYbr14cQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-07-07T19:15:57Z"
    mac: ENC[AES256_GCM,data:p7aZDCzM5c3lDMk9rFhMBdNivmBq7lsHO3hU9vgroS3J/8OJGTWDrL/c9dYG2AMFAmfqOmTPaoX3inwGb/J/XxZg8UmvnvDsyPa352BKgimQx+nyHQ4otEQz+dNrW5bW8/njQWwKXeXHRsbB/rfmpeo7kPHPUNGDEAPUq+Z9SFc=,iv:8jmQzPUGsg/fpqKSqkrMFEwKLmaz6rmnx+fFsukY9z4=,tag:/1YNGO2TxUnb3zGGcrcWfg==,type:str]
    version: 3.13.2
