apiVersion: v1
kind: Secret
metadata:
    name: github-credentials
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ENxgwS5WNA==,iv:B2IvZCXm/1+p3+OIRKnh4Mmot8L3xiAqKn51EOSyeq4=,tag:JmnTi8xeWvI8fhoNriiLrQ==,type:str]
    password: ENC[AES256_GCM,data:GttWf+9ItodeH6QHKKR/xPTl+8NIlrH9X7MsSurXoE7g/zcMIQ7PLA==,iv:N2ipf+InllNS+lOfImj5Xs+CEzSabLN8UsPjgZTHzY8=,tag:RurHRF59HpzlUoupIRD0qQ==,type:str]
    github_token: ENC[AES256_GCM,data:WXpfpE9CXjhuswSCl8jzx1w5iDnNgBV1Tz1o9BxhGSdkAIaajmjH2Q==,iv:GzMFr23IC69729mbyQ6R4uWb5dPbqXD6hbPYD6tvMhw=,tag:m2BiHngZiHn0zgUpRmpzzg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeTYzcjYwZGczVUhwUDJR
            Z0lwcFlRTjkrY2gxVVpYcm1Ncld6ZGgwbWdJCnkyUklIVzc5QnRmZG9FWG9rKzhm
            aTlweVVQYmVWYTNlcStmQ2wyT0hkdW8KLS0tIHZqczBqU21EUVVoU2cwKzMraDR0
            QWtMZ3ZRc29SVWt4OTBoMDREa2dxRzgKalUiC3o3+gnkn+rDIjuVka7SJofZe9yW
            3G0FP2DT+h/kutpsXwBMonm0smZhssxNRKfsHtwFZhBROKAmCC9avw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-06-30T13:28:09Z"
    mac: ENC[AES256_GCM,data:3nK8u/O/Ai+EvAoVO5ooh6OhNXQomjqZVt/ViEOKS+rfcP++YaYqgK/u4cQwtuPmopr/kuSbEC3oQmkFd294vOhI5IVZ387S8VuSuLgtAMyLSJK7Cei3kg4T8FpqHzWVS4Eho7rmw3OF52x5jVflC0K3OECe90r11+mNFbbNwxo=,iv:m/2+AVqCuLUp5GRVNXZWlAxD0gnR8toPbS3HqU1y9Gw=,tag:ENmZIblwI5Wo7CSubpMWxA==,type:str]
    version: 3.13.1
