apiVersion: v1
kind: Secret
metadata:
    name: github-credentials
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:/OIgnjrHsg==,iv:eHPWEwCD/gU+ORTD25Qhs93CCsrHhdzxTT5AZW271Vo=,tag:miLTP0psnoJOtiF+9Hr09Q==,type:str]
    password: ENC[AES256_GCM,data:C9/2Beix12RsIsM/W6s5ian3DwWykc9UEY3ifTV79P/wzyN9kz6trQ==,iv:biwREYFHf0lhZMuxLJRrJqxs6hIVzfL+C87jf2y6JLw=,tag:FCPpGeHqdBsJgd30S/6QRg==,type:str]
    github_token: ENC[AES256_GCM,data:j5EkIMIcXGrq1hHAKnXm6E49FiKw3QNRE1JJmWus/bqNhHy0OT1vrA==,iv:1xpkCmLmr4cNdy/EUppebahdRuWeEV0g1E75AzJFsrU=,tag:yCBWeL7BPMrrjRkBTjLCvg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ0piWWJuRHozRWVZbmtO
            dVppRUJ1dm1Fc0J6N0Nsc0o2VXNKTVRRVFg4CkJlSmZmekt4SkcxWVdkNlg3bWR2
            dUhmVVZzYWg1UnN2d0VYQ3VwdUptVGsKLS0tIG1IM2JocXZPM1VFc1NjVWZORExB
            ekVQWGpnM2piUDFDT0gvTzhPYjFEZEkKvKjCdB5nGAAC1HBybTpmG4qlREZfB8yc
            7ZgW9KiXrKAAnKq5/PDdYyAfM89mkBOhEeouUN6lkWJUUOjUIVjgmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-06-30T12:30:14Z"
    mac: ENC[AES256_GCM,data:VbLh4rZN3oW8hKPYdV+sEDOXk/uTl3EAXnU8ynWyFthZqUpWAc5i0P5Hwu8a73I+zSkkgLaqx0x3dPsJKBqGU1VWIYgzqrgiqoXICSf0ryX3hCPMYT6EEvCQkrbjr+wBX6Sewdi/omvsB+JlA8Pf5J1T9AT+s5VrDWIEujwK0jo=,iv:Tey+DUuRuAlHxxC9wKFU9lDs+98NHjBdM1crPowrQAQ=,tag:P2KbtVP6//ogZj5VOUWMnA==,type:str]
    version: 3.13.1
