apiVersion: v1
kind: Secret
metadata:
    name: github-credentials
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:i+kGjZnD+w==,iv:VYdanXLksrAdOPh8M++6ZlhdHosmwptsrJUZVLsIYsg=,tag:oFCx88BJmuiue62NEjiDsQ==,type:str]
    password: ENC[AES256_GCM,data:jNbibPxCW17Gx2NhViZb9vXYJeqvGZHR+0SrMUuVQ/T2BSw3lwzooA==,iv:1CTFsVYFlyBk8g1ULT9G9pgTJHEMgJlXnFvTeDCCJxM=,tag:ffrHyrrxmOBcMtpfS7WUiw==,type:str]
    github_token: ENC[AES256_GCM,data:SEEgjrGvyHkIP2RzmYylDeGX9sZD9V9L/bkGENCCWG2yL9jBBjpmHg==,iv:oQkjaIZN4mR3IRkinqdVoQVAEV2G3uPIf2GgU9jykFg=,tag:A1mLPrb/7rF0Lb74J/Ur0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUFdlVWNBU1RTWm1nd1Az
            cWJ6bjRuRnNnMmRyR1VjQ1hrM1VvS1ZONFRZCnFJWFgwVlcrc1pZakJGL3ozMG13
            M3IvSWM0SDVtMXM3R0hKVC9LQmcxVlkKLS0tIEgrRXBMS3lTaGFvN2JtUFJ5ZHE5
            eFkrK01saTZ2Y2xnS0FIakkyLytGOUkK8dZaKPeUmXhjnOyjzvw+mAgYVsPnymR6
            uU35f5h9zbBaOSkU0qVJF/vAs2l3CSTwEaHdrwkpjF5m9krB3Wgm6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-06-30T13:35:48Z"
    mac: ENC[AES256_GCM,data:uCh4pJZBLuhRp3oyJz52o/MOGvnd0oD0XLdXyLe5Il+eBjDZ1E/hlixTLx7qVUyVVJhcifXlJvpHGo2ZLta8v1lxmCSSJZTc4B/p3hUrTX0IYsLjjDuQEk3J9euvfIi7oUGTTzNY/1lyFsecQ/bMBeOYC0fX9iwkAilL2bTaxEc=,iv:VX+JCLfoXAp6zgiA7dVA6mF1faoKNpRyw7rbN5arueY=,tag:MWOyglxfPL7SWG3zNG0Rkg==,type:str]
    version: 3.13.1
