apiVersion: v1
kind: Secret
metadata:
    name: gitlabcom-credentials
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:BRc06dC2,iv:UQLgZPqGMQm7b2vpCLTRra8mf+l8/TrVbwEpWyvVxds=,tag:rUf6IzkfuB9iuvs84GyeyA==,type:str]
    password: ENC[AES256_GCM,data:f2/JGweT8UqcrnIlcn3MBOFWb969zvs9omY/P/1gVcW5T3a4N06ys5u7hgmbyC8BmV8UFPq989cPGjM=,iv:wOBNf4E7tF3VYiaYeOEanq9yw+5H/rgs6/X7OtJ+5Sc=,tag:aszDiSuFQLkpvWSPKZMvwA==,type:str]
    gitlab_token: ENC[AES256_GCM,data:x26NHs1ukIBdOvana0zq6xie6EOWAJtGYUq5dy7SWm46+AIGX/R33eByaHLqwpKoK71OzFsYxMdwvXk=,iv:PSKYUK0yjfcCwLkAsh6glhr9/FQorVfeU9m1uvQUugs=,tag:sq0bsiqx7/zveQ+7idl37g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaytwS3hSMjBRZ1c2elQ5
            L0t5QnRhd1RDYVNqL0tQWWhXQWJML1Z2eGpFCmRMWWF2cDhsV2RiNGs2V3pHc1pj
            Z3lTbFluWHYwU2xwV0VHN3BBbHNlNGsKLS0tIEFiT3ROR0hNd2o3ZjVkSzZOWjg0
            UTNGWTFwOGxXT0tZU2ZIYzdOeC9OTW8KDhFfBqY/NYbr47aGKUtP8hURtTAM1M5T
            XZiGS4802d7RpJevDYy9H47hSWQJwkrTQfbLPfs20fAj6DpjAxINJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-07-10T12:41:25Z"
    mac: ENC[AES256_GCM,data:IsOb4/pKVhvXL6KCmQhJZrWJJqEbpgHSNk2MCem+mL6ASKdJpHGVTLjPxqFtVuoKMLV4VsW09UKAlnkyAKOD5OPca0BGjJ7yAVt4bWlVWweEukkV2yv6dC3mN+zp3Y5azq+lnOKV5cFjl+whtgG4b+KQSbtAf8wELubhjCae4Go=,iv:a+fJU1ytiQgUfHvTYCYopKCdaRhz8l8f1/pN10wrsdY=,tag:40uSKBW7Dc7CYXgDynOT+g==,type:str]
    version: 3.13.2
