apiVersion: v1
kind: Secret
metadata:
    name: gitlab-tf-credentials
    namespace: flux-system
type: Opaque
data:
    gitlab_token: ENC[AES256_GCM,data:YxTFYdt2eRNQWIeioouZRA30iYQUckRkpJsuA66Hn11zQYe6x9/WFKUlhk9myxOZPoDBHpXiWszCtmJQqAB6mFm1QuY=,iv:i6wacDJOg8PV7LANwgT/JhQZuxk7kW596nedUo5nYFY=,tag:6xtRtg8LdE5vM5Of4HDiJA==,type:str]
    password: ENC[AES256_GCM,data:Cppd5cqvoaLah0xwtMiZnkxDfwi2FHvKa5OnlTXcrpLXOkZn1oBD+YB2GpLfK7ps1x/jcF4pNUd2mVtECYNBXSavTr4=,iv:CxKYaRWjrYEQBUUEV5jIPtFhH7uPl1gmdijjm/Y1Maw=,tag:L3VWr9FBhiUL9CiCLEFLxg==,type:str]
    username: ENC[AES256_GCM,data:L9ulZ+APONg=,iv:EutMKR60E8WnqR69w4al62hRsL5ZygFn/9AO1PDmJOk=,tag:enUuSXh1/boijc+cTspYwA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsejNNb3dSS2ZoeHZwK05i
            TW5mVGEwOXVoL1JsSW02SXcreFN6WnNHdXpVCmdid0gvTE90ZUltNGJYbURSS3Qz
            Vm43MEhPQUNGNFJDTnZ6NHhBQ1lCaTAKLS0tIFZhM0d0WkVvQ0RNc0JVb0JHMVRt
            eDgzR2xJN2FRTGI0WDRoajZKSFVtMzQKwC26GyLSESIiNzlTA8c9wiZfm+OT1s2J
            A/++aA1Ue2tFp85kcEIt1Nen5Q78q0FTaT3H/guz92thV48MG1GAqA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T07:58:04Z"
    mac: ENC[AES256_GCM,data:SAEwf1yMvYOdWNWC6oc0y2+InGC/5Dw1gTu/vMuhnCHmoBwKBoJyk2G9+LfRfRFyycPhxgBmxSjOyWup6hbYJg+WnDrQWmmlVGB3ZHYke/lOImKEbzSWuvgCVM4i0pYqk/dGiBcWZCKAIz50BDjoPFcIPIrgJztIxKw1+qziD44=,iv:BxsoRkRi8NboCTxR21YXcAdiRttcAg/Ilw3CElELUeE=,tag:BlyBxTb+8hOiU6LcLpAzQg==,type:str]
    version: 3.13.1
