apiVersion: v1
kind: Secret
metadata:
    name: gitlabcom-helloworld-iac-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
    type: ENC[AES256_GCM,data:OKDq,iv:ozarfsuShJZtB9lDW2dMZM/aodYtdVHCC6tBxOFnKUM=,tag:EF9B1JWB7t1Cz0mOli4ytA==,type:str]
    url: ENC[AES256_GCM,data:kOjWbakxhww0G2M+UQjvHCzxRK5+flAIl6Z+g4cIL+izd/c4sW1GNTe+aWqrN6uoIHSyroJiqchOiNgZwRmhNoM=,iv:JbjxwK3bU51LIG00RyjcHGAfhgYe1Ef0zp/RGeGerho=,tag:iauwp5MZ9Dd/SWRLWaTg8A==,type:str]
    username: ENC[AES256_GCM,data:W86ZWAgA,iv:ymhsf6drMxllyjfma+AN0dXWhNIitPoWER8MntF3tfk=,tag:5l2zxxhYqqJNDSUIqgczDg==,type:str]
    password: ENC[AES256_GCM,data:InBKKcueXJaQvKh+sLFm4bG11Vf1PQFDJdKwzq2VL98lyCJcDREdCcpHuLrRKvES/1lFmBO2Z5Sx0ZE=,iv:twabHIusFCVYMOeNcaHLtawYnSylK86Yy4taMUKr8iQ=,tag:T8rcL7wxexI/Ondd84DoPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORHplYnNYbGVkRGRxeHY5
            N0xiUFJwNlBtdWNEZGxlbU1McmhKWmxTM0MwClliemhSL2hoSlFQcTBFZ1F4YmZn
            UDFnNU5kQjlONFp3bUpyTy9yYXpLSncKLS0tIElNY1ZlZTNJY3A5WG81VTdXUk1R
            WHNTZkNaNDdEQ1ZsK0dmNkx3Y0cxQ00K2cwB3yLum4OPR0YA/8njk+7YQzfDuXmQ
            g1fgx3pzI5ikcyiSc/fUzG0rT1N+kFmS1342Bxa6Penggh6VITMwPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-07-10T13:38:20Z"
    mac: ENC[AES256_GCM,data:5ZYOtm4Y9V1T8n74ULvOnGgbaOFkQ/QsMhBa2i6nDyEOXFcAmQIfsJujf5AHxh/+bxhPARxoGHA+9JODwdrDND0UewfbX5IfUn7zKqLoicxC50OjdumNElf4d1jmaTZPmLupU3CA8w8duSJbeghTM2yVaorxYUjNCpsEGoqIAVU=,iv:+1iP5rGZmJnmKvo6DfdfpY62q4fw6TdeQyciX9wTtDw=,tag:6FIgbUGpjfpouc5aHQOQ7Q==,type:str]
    version: 3.13.2
