apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud-credentials
    namespace: argocd
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:IDuy/nuPVscABuuRcFUMsZ0UvEQSXcDqTygrdYtcdfgg48dAlFPMMmE+yiuOucr4jlmaslnKw0ACb+9P2i6FK/pXGTBmjjAg5G9E6UG/02/DySM4SyClCTxgYhnKPEAVW8ACLMb7qW7Siz9oY+cMeA==,iv:uKWCjHDBYsdgPxwjtCKGSOXVWRRTeJCbqtwW/qtbxSw=,tag:/tCjqmpNOqPkC+ccJuelgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONk81OGpYMjF3YktMMWFT
            KzEyRnlQenFuM1NsTFFGYXJBRDVwQjNTUEhNCmNwTWh2V0V6WW9LOGY5Vk1RTTZI
            WHJSdjhFMEdGV1p2ekk2cU5leEMvWE0KLS0tIGJzVndZejN2NW9hR3BNdzVKQ1lr
            bTJDVWsvZkZtTytWb3Nxa1dnKzBjd0EKClxK5X+jeMl23H4ZWOjdcWZdIzSFmBMF
            lGhCqQH2KbcAVg3G8LgZsocKKepUtNSE7cJzvAf0Oxso+LWMNAqRCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age136dut7ljt7angdg84vpdldfqqgd4hv64la7afc80z0c67k68nq8s2sj6yz
    encrypted_regex: ^(stringData|data)$
    lastmodified: "2026-07-10T06:08:02Z"
    mac: ENC[AES256_GCM,data:wHUXYYotwljnR6g/0eRLcxxVq3k3LIoXGpIUXBJRrOnULgkxkXIt5fuZgxk4cRocv1rzBsCQHW66Xx8PDd86YVbfoQFIBEcyl44qx2TYJ7S8pL8xt8cbzQjzil5Ux40wzJWkja8HBE3BHOERoQ3+lc0VI5Y8d/NSB2xvThJSN7g=,iv:3o7+/X1Vs3gbdc05LfATdN6tcpUw/9D9fuyALctJNe8=,tag:kEfeJFyclY6a1PXY+bryZg==,type:str]
    version: 3.13.2
