apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: platform-gitops
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  interval: 5m
  url: https://github.com/poc-devops-elkouhen/platform-gitops.git
  ref:
    branch: main
