apiVersion: v1
kind: Service
metadata:
  name: argocd-dex-server
  namespace: argocd
  labels:
    app.kubernetes.io/component: dex-server
    app.kubernetes.io/name: argocd-dex-server
    app.kubernetes.io/part-of: argocd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: argocd-dex-server
  ports:
    - name: http
      appProtocol: http
      port: 5556
      protocol: TCP
      targetPort: 5556
    - name: grpc
      port: 5557
      protocol: TCP
      targetPort: 5557
    - name: metrics
      port: 5558
      protocol: TCP
      targetPort: 5558
